implement and test task 3 GET /api/topics
Calor94/news-api pull request #2
Opened 2023-05-09 15:03 UTC by Calor94

2023-05-09 15:27 UTC, mezzDavies requested changes
Looking good but we could consider a couple of errors here - a generic 404 that can be tested for and a 500 internal server error that cannot be tested for but should be in place.

Have a look [here](https://notes.northcoders.com/courses/js-back-end/error-handling) for examples of the way to handle errors 😄 

Please put these in place and then resubmit your PR. 👍

2023-05-09 15:27 UTC, mezzDavies commented on app.js
> +app.use(express.json());
We don't need this just yet - it is good practice to only have code in place that is being used.

2023-05-09 15:27 UTC, mezzDavies commented on __tests__/app.test.js
> +        res.body.topics.forEach((topic) => {
There should be an assertion here checking the length of the array is correct before the forEach. If we don't then we could get a false positive.

2023-05-10 09:24 UTC, HannahBurks approved these changes
Nice work Callum 😄  Get it merged! 👏🏼

2023-05-10 09:24 UTC, HannahBurks commented on app.js
> +  console.log(err);
just a note to remove any console logs before pushing to github :)

2023-05-10 09:34 UTC, merged